string(APPEND CONFIG_ARGS " --host=cray")
if (COMP_NAME STREQUAL gptl)
  string(APPEND CPPDEFS " -DHAVE_NANOTIME -DBIT64 -DHAVE_SLASHPROC -DHAVE_GETTIMEOFDAY")
endif()
<<<<<<< HEAD
string(APPEND CMAKE_C_FLAGS_RELEASE " -O2 -g")
string(APPEND CMAKE_Fortran_FLAGS_RELEASE " -O2 -g")
=======
string(APPEND SLIBS " -L$ENV{CRAY_HDF5_PARALLEL_PREFIX}/lib -lhdf5_hl -lhdf5 -L$ENV{CRAY_NETCDF_HDF5PARALLEL_PREFIX} -L$ENV{CRAY_PARALLEL_NETCDF_PREFIX}/lib -lpnetcdf -lnetcdf -lnetcdff")
set(CXX_LINKER "FORTRAN")
set(NETCDF_PATH "$ENV{NETCDF_DIR}")
set(NETCDF_C_PATH "$ENV{NETCDF_DIR}")
set(NETCDF_FORTRAN_PATH "$ENV{NETCDF_DIR}")
set(HDF5_PATH "$ENV{CRAY_HDF5_PARALLEL_PREFIX}")
set(PNETCDF_PATH "$ENV{CRAY_PARALLEL_NETCDF_PREFIX}")
if (NOT DEBUG)
  string(APPEND CFLAGS " -O1")
  #string(APPEND CFLAGS " -O0 -g")
endif()
if (NOT DEBUG)
  string(APPEND FFLAGS " -O1")
  #string(APPEND FFLAGS " -O0 -g -fbacktrace -fcheck=all -Wall")
endif()
string(APPEND CXX_LIBS " -lstdc++")
>>>>>>> First commit on SAI/eam/chem/tsmlt
set(MPICC "cc")
set(MPICXX "CC")
set(MPIFC "ftn")
set(SCC "gcc")
set(SCXX "g++")
set(SFC "gfortran")
